FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY server/package*.json ./server/

# Install dependencies
RUN npm install --only=production
RUN cd server && npm install --only=production

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Command to run the app
CMD ["node", "server/index.js"]